MODEL_PATH=./model/ViRC-7B-stage2
TRAIN_FILES=./data/ViRC_stage_3_StratRL_train_scale_dynamic.parquet
VAL_FILES=./data/ViRC_stage_3_StratRL_val_scale_dynamic.parquet

DEFAULT_LOCAL_DIR=./model/ViRC-7B
PROJECT_NAME=StategicRL
EXPERIMENT_NAME=ViRC-7B

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
mkdir -p $DEFAULT_LOCAL_DIR
cd $DEFAULT_LOCAL_DIR
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
python3 -m verl.trainer.main_ppo \
    +actor_rollout_ref.actor.freeze_vision_tower=True \
    +model.use_liger=True \
    actor_rollout_ref.actor.checkpoint.save_contents='["model"]' \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.clip_ratio_low=0.2 \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.path="$MODEL_PATH" \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=True \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.limit_mm_per_prompt='{'image': 64}' \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.max_num_batched_tokens=8192 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
    algorithm.adv_estimator=grpo \
    algorithm.kl_ctrl.kl_coef=0.001 \
    algorithm.use_kl_in_reward=False \
    data.filter_overlong_prompts_workers=64 \
    data.filter_overlong_prompts=True \
    data.max_prompt_length=8192 \
    data.max_response_length=512 \
    data.train_batch_size=64 \
    data.train_files="$TRAIN_FILES" \
    data.truncation='error' \
    data.val_files="$VAL_FILES" \
    reward_model.launch_reward_fn_async=True \
    reward_model.reward_manager=prime \
    trainer.critic_warmup=0 \
    trainer.default_local_dir="$DEFAULT_LOCAL_DIR" \
    trainer.experiment_name="$EXPERIMENT_NAME" \
    trainer.logger='["tensorboard"]' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.project_name="$PROJECT_NAME" \
    trainer.save_freq=10 \
    trainer.test_freq=9999 \
    trainer.total_epochs=1 \
    trainer.val_before_train=False
